### ISSUE TITLE
Garrtbrayn_Inno

### ISSUE THREAD

**Issue by Garrybrayn** [cosmos/chain-registry#3204]
> 
[Документ_1204384(2).pdf](https://github.com/cosmos/chain-registry/files/13366802/_1204384.2.pdf)
https://github.com/cosmos/chain-registry/blame/c99fe60b950b75aa15f6cdeec33037573bf8a485/cosmoshub/chain.json#L1
```[sprint]
### Tasks
- [ ] https://github.com/cosmos/chain-registry/pull/3198
- [ ] https://github.com/cosmos/chain-registry/pull/3197
```

```[sprint]
### Tasks
- [ ] https://github.com/cosmos/chain-registry/pull/5150
```

**Comment by Garrybrayn** [comment]
[Uploading Документ_1212312.pdf…]()

**Comment by JeremyParish69** [comment]
Anything else required here?

**Comment by Garrybrayn** [comment]
![Screenshot_2024-08-13-23-33-50-270_org telegram messenger-edit](https://github.com/user-attachments/assets/a9e1b5a6-72c4-4e3a-821a-04954cefbc65)

**Comment by Garrybrayn** [comment]
👍👍👍
